### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by SpoonOfDoom** [Bio2hazard/SteamCompletionist#12]
Hey, just wanted to give you a heads up that the SteamCompletionist site has been down for a few days now, in case you didn't notice. It loads a while, then nginx returns a 502 error.
Or did you decide to turn it off?

**Comment by SpoonOfDoom** [comment]
I'm just gonna bump this instead of making a new issue. Site seems to be down again, again with a 502.

**Comment by Bio2hazard** [comment]
All fixed @SpoonOfDoom sorry about that! A service broke and produced an ungodly amount of logs causing disk space to fill up.
