### ISSUE TITLE
Site is currently down and didn't add new entries before that

### ISSUE THREAD

**Issue by primapresto** [Bio2hazard/SteamCompletionist#14]
Hey there.

The site has been down for over a week. Any chance to get it up and running again?

I also noticed that before it went down, it didn't add new games, I had added to my library. Could perhaps be due to a rather large Steam library (5000+ games)?

**Comment by Bio2hazard** [comment]
Hi @primapresto thank you for reporting the problem. Should be all fixed! Took a bit of doing.

Adding new games and the page loading should work just fine. Steam updated their api and removed a property I was relying on but I was able to work around it.

Congrats on that sizeable library! I'm about to reach 2600 so I still have a ways to go :)

**Comment by enesfarukmeniz** [comment]
How did you handle removal of img_logo_url? Will you commit your fix? 😅
