### ISSUE TITLE
Sample config file?

### ISSUE THREAD

**Issue by beporter** [Bio2hazard/SteamCompletionist#4]
Is there a sample config file stored in the repo? The `httpdocs/index.php` file [references](https://github.com/Bio2hazard/SteamCompletionist/blob/3a136a/httpdocs/index.php#L17) a `../private/Config.php` but an example of what that file looks like doesn't seem to be included. Am I missing it?

**Comment by Yugge** [comment]
Adding this here if anyone else is searching for it in the future: https://github.com/SpoonOfDoom/SteamCompletionist/blob/master/private/Config_Sample.php

**Comment by SpoonOfDoom** [comment]
I've been meaning to do a pull request for ages, but always stuck on "I'll do it when I made change X". I'll do one later today, which also contains the database structure.

**Comment by Bio2hazard** [comment]
Just wanted to pop in and say that pull requests are very welcome. :)
Sorry for the lack of a sample config file.

The site is back up by the way!

I'm still around and I would love to show steamcompletionist.net some love.

**Comment by Bio2hazard** [comment]
Added the config file in c879f030cbc30d4b90140edad6517c422fdf5ff1.
