### ISSUE TITLE
Fatal Error on Main Page

### ISSUE THREAD

**Issue by zeke8402** [Bio2hazard/SteamCompletionist#6]
Hello,
Using this app today I was met with a Fatal SQL error on login
![firsterror](https://cloud.githubusercontent.com/assets/1671173/24636408/a37b26c4-189f-11e7-9151-0db55b44858d.png)

The two errors behind it are as follows:

`Notice: Undefined variable: logger in /var/www/vhosts/steamcompletionist.net/httpdocs/index.php on line 151`

` Fatal error: Call to a member function addEntry() on a non-object in /var/www/vhosts/steamcompletionist.net/httpdocs/index.php on line 151`

**Comment by Bio2hazard** [comment]
Hey, sorry for the delay in responding here. One of the server processes hung. I fixed it a day after you created the issue.

Thank you for bringing it to my attention!
