### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Vekter000** [Bio2hazard/SteamCompletionist#7]
I am getting a generic error message when trying to access the website. Is it still being supported?

Thank you.

Error message:
This site can’t be reached

www.steamcompletionist.net refused to connect.
Search Google for steam completionist net
ERR_CONNECTION_REFUSED

**Comment by Bio2hazard** [comment]
Fixed! I definitely am continuing to host it. Sorry for the hassle. The server had some technical issues that are now resolved. 👍
