### ISSUE TITLE
Game with 100% Achievements Isn't shown as 'Completed'

### ISSUE THREAD

**Issue by Zunon** [Bio2hazard/SteamCompletionist#8]
Game in case: Thomas was alone, http://www.steamcompletionist.net/76561198044211895/
I finished all achievements for this game a while back, it isn't marked as 'completed', only 'beaten', how do I mark it completed?

**Comment by SpoonOfDoom** [comment]
Duplicate of #1, I think.

**Comment by Bio2hazard** [comment]
Yes, that is correct. Completed is only for the pie-chart in the top left. I'll see if something can be done to make it a better-integrated status and change the border color!

**Comment by Zunon** [comment]
@Bio2hazard Looking forward to seeing this.
